package com.fifa.ubosque.worldcup.entities;

// Generated 6/05/2014 08:40:07 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Estadios generated by hbm2java
 */
@Entity
@Table(name = "estadios", catalog = "worldcup2014")
public class Estadios implements java.io.Serializable {

	private Integer id;
	private String nombreOficial;
	private String sede;
	private int capacidad;
	private String temperatura;
	private Set<Partidos> partidoses = new HashSet<Partidos>(0);

	public Estadios() {
	}

	public Estadios(String nombreOficial, String sede, int capacidad,
			String temperatura) {
		this.nombreOficial = nombreOficial;
		this.sede = sede;
		this.capacidad = capacidad;
		this.temperatura = temperatura;
	}

	public Estadios(String nombreOficial, String sede, int capacidad,
			String temperatura, Set<Partidos> partidoses) {
		this.nombreOficial = nombreOficial;
		this.sede = sede;
		this.capacidad = capacidad;
		this.temperatura = temperatura;
		this.partidoses = partidoses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "nombre_oficial", nullable = false, length = 100)
	public String getNombreOficial() {
		return this.nombreOficial;
	}

	public void setNombreOficial(String nombreOficial) {
		this.nombreOficial = nombreOficial;
	}

	@Column(name = "sede", nullable = false, length = 100)
	public String getSede() {
		return this.sede;
	}

	public void setSede(String sede) {
		this.sede = sede;
	}

	@Column(name = "capacidad", nullable = false)
	public int getCapacidad() {
		return this.capacidad;
	}

	public void setCapacidad(int capacidad) {
		this.capacidad = capacidad;
	}

	@Column(name = "temperatura", nullable = false, length = 100)
	public String getTemperatura() {
		return this.temperatura;
	}

	public void setTemperatura(String temperatura) {
		this.temperatura = temperatura;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estadios")
	public Set<Partidos> getPartidoses() {
		return this.partidoses;
	}

	public void setPartidoses(Set<Partidos> partidoses) {
		this.partidoses = partidoses;
	}

}
