package com.fifa.ubosque.worldcup.entities;

// Generated 12/05/2014 04:16:43 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Grupos generated by hbm2java
 */
@Entity
@Table(name = "grupos", catalog = "worldcup2014")
public class Grupos implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private Set<Equipos> equiposes = new HashSet<Equipos>(0);

	public Grupos() {
	}

	public Grupos(String nombre, Set<Equipos> equiposes) {
		this.nombre = nombre;
		this.equiposes = equiposes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "nombre", length = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "grupos")
	public Set<Equipos> getEquiposes() {
		return this.equiposes;
	}

	public void setEquiposes(Set<Equipos> equiposes) {
		this.equiposes = equiposes;
	}

}
