package com.fifa.ubosque.worldcup.entities;

// Generated 12/05/2014 04:16:43 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Jugadores generated by hbm2java
 */
@Entity
@Table(name = "jugadores", catalog = "worldcup2014")
public class Jugadores implements java.io.Serializable {

	private Integer id;
	private Equipos equipos;
	private String nombre;
	private String edad;
	private String posicion;
	private Set<RankingJugadores> rankingJugadoreses = new HashSet<RankingJugadores>(
			0);

	public Jugadores() {
	}

	public Jugadores(Equipos equipos, String nombre, String edad,
			String posicion) {
		this.equipos = equipos;
		this.nombre = nombre;
		this.edad = edad;
		this.posicion = posicion;
	}

	public Jugadores(Equipos equipos, String nombre, String edad,
			String posicion, Set<RankingJugadores> rankingJugadoreses) {
		this.equipos = equipos;
		this.nombre = nombre;
		this.edad = edad;
		this.posicion = posicion;
		this.rankingJugadoreses = rankingJugadoreses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_equipo", nullable = false)
	public Equipos getEquipos() {
		return this.equipos;
	}

	public void setEquipos(Equipos equipos) {
		this.equipos = equipos;
	}

	@Column(name = "nombre", nullable = false, length = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "edad", nullable = false, length = 2)
	public String getEdad() {
		return this.edad;
	}

	public void setEdad(String edad) {
		this.edad = edad;
	}

	@Column(name = "posicion", nullable = false, length = 100)
	public String getPosicion() {
		return this.posicion;
	}

	public void setPosicion(String posicion) {
		this.posicion = posicion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jugadores")
	public Set<RankingJugadores> getRankingJugadoreses() {
		return this.rankingJugadoreses;
	}

	public void setRankingJugadoreses(Set<RankingJugadores> rankingJugadoreses) {
		this.rankingJugadoreses = rankingJugadoreses;
	}

}
