package com.fifa.ubosque.worldcup.entities;

// Generated 6/05/2014 08:40:07 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RankingEquipos generated by hbm2java
 */
@Entity
@Table(name = "ranking_equipos", catalog = "worldcup2014")
public class RankingEquipos implements java.io.Serializable {

	private Integer id;
	private Equipos equipos;
	private int partidosJugados;
	private int partidosEmpatados;
	private int partidosPerdidos;
	private int puntos;
	private int golesFavor;
	private int golesContra;
	private int diferenciaGol;

	public RankingEquipos() {
	}

	public RankingEquipos(Equipos equipos, int partidosJugados,
			int partidosEmpatados, int partidosPerdidos, int puntos,
			int golesFavor, int golesContra, int diferenciaGol) {
		this.equipos = equipos;
		this.partidosJugados = partidosJugados;
		this.partidosEmpatados = partidosEmpatados;
		this.partidosPerdidos = partidosPerdidos;
		this.puntos = puntos;
		this.golesFavor = golesFavor;
		this.golesContra = golesContra;
		this.diferenciaGol = diferenciaGol;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_equipo", nullable = false)
	public Equipos getEquipos() {
		return this.equipos;
	}

	public void setEquipos(Equipos equipos) {
		this.equipos = equipos;
	}

	@Column(name = "partidos_jugados", nullable = false)
	public int getPartidosJugados() {
		return this.partidosJugados;
	}

	public void setPartidosJugados(int partidosJugados) {
		this.partidosJugados = partidosJugados;
	}

	@Column(name = "partidos_empatados", nullable = false)
	public int getPartidosEmpatados() {
		return this.partidosEmpatados;
	}

	public void setPartidosEmpatados(int partidosEmpatados) {
		this.partidosEmpatados = partidosEmpatados;
	}

	@Column(name = "partidos_perdidos", nullable = false)
	public int getPartidosPerdidos() {
		return this.partidosPerdidos;
	}

	public void setPartidosPerdidos(int partidosPerdidos) {
		this.partidosPerdidos = partidosPerdidos;
	}

	@Column(name = "puntos", nullable = false)
	public int getPuntos() {
		return this.puntos;
	}

	public void setPuntos(int puntos) {
		this.puntos = puntos;
	}

	@Column(name = "goles_favor", nullable = false)
	public int getGolesFavor() {
		return this.golesFavor;
	}

	public void setGolesFavor(int golesFavor) {
		this.golesFavor = golesFavor;
	}

	@Column(name = "goles_contra", nullable = false)
	public int getGolesContra() {
		return this.golesContra;
	}

	public void setGolesContra(int golesContra) {
		this.golesContra = golesContra;
	}

	@Column(name = "diferencia_gol", nullable = false)
	public int getDiferenciaGol() {
		return this.diferenciaGol;
	}

	public void setDiferenciaGol(int diferenciaGol) {
		this.diferenciaGol = diferenciaGol;
	}

}
