package com.fifa.ubosque.worldcup.entities;

// Generated 11/05/2014 02:01:12 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Descripcion generated by hbm2java
 */
@Entity
@Table(name = "descripcion", catalog = "worldcup2014")
public class Descripcion implements java.io.Serializable {

	private Integer id;
	private String evento;
	private String momento;
	private int idPartido;

	public Descripcion() {
	}

	public Descripcion(String evento, String momento, int idPartido) {
		this.evento = evento;
		this.momento = momento;
		this.idPartido = idPartido;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "evento", nullable = false, length = 65535)
	public String getEvento() {
		return this.evento;
	}

	public void setEvento(String evento) {
		this.evento = evento;
	}

	@Column(name = "momento", nullable = false, length = 100)
	public String getMomento() {
		return this.momento;
	}

	public void setMomento(String momento) {
		this.momento = momento;
	}

	@Column(name = "id_partido", nullable = false)
	public int getIdPartido() {
		return this.idPartido;
	}

	public void setIdPartido(int idPartido) {
		this.idPartido = idPartido;
	}

}
