package com.fifa.ubosque.worldcup.entities;

// Generated 11/05/2014 02:01:12 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * EstadosPartidos generated by hbm2java
 */
@Entity
@Table(name = "estados_partidos", catalog = "worldcup2014")
public class EstadosPartidos implements java.io.Serializable {

	private Integer id;
	private String estadoPartido;

	public EstadosPartidos() {
	}

	public EstadosPartidos(String estadoPartido) {
		this.estadoPartido = estadoPartido;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "estado_partido", length = 100)
	public String getEstadoPartido() {
		return this.estadoPartido;
	}

	public void setEstadoPartido(String estadoPartido) {
		this.estadoPartido = estadoPartido;
	}

}
