package com.fifa.ubosque.worldcup.entities;

// Generated 11/05/2014 02:01:12 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Perfiles generated by hbm2java
 */
@Entity
@Table(name = "perfiles", catalog = "worldcup2014")
public class Perfiles implements java.io.Serializable {

	private Integer id;
	private String nombrePerfil;

	public Perfiles() {
	}

	public Perfiles(String nombrePerfil) {
		this.nombrePerfil = nombrePerfil;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "nombre_perfil", nullable = false, length = 100)
	public String getNombrePerfil() {
		return this.nombrePerfil;
	}

	public void setNombrePerfil(String nombrePerfil) {
		this.nombrePerfil = nombrePerfil;
	}

}
